import { Link } from 'react-router-dom';
import { ArrowDown, Check, ClipboardList, LockKeyhole, Sparkles } from 'lucide-react';
import RegistrationForm from '../components/RegistrationForm';

export default function HomePage() {
  return <main>
    <header className="site-header"><a href="#top" className="brand aicpes-brand" aria-label="AICPES, accueil"><img src="/aicpes-logo.png" alt="AICPES" /></a><nav><a className="nav-link" href="#etapes">Comment ça marche</a><a className="button button-outline nav-admin" href="/admin">Espace administrateur <LockKeyhole size={15} /></a></nav></header>
    <section className="hero" id="top"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-content"><span className="hero-kicker"><Sparkles size={14}/> AICPES · INSCRIPTIONS OUVERTES</span><h1>La prochaine étape<br/>commence <span>ici.</span></h1><p>Rejoignez l’AICPES. Complétez votre inscription en ligne, simplement et en toute sécurité.</p><a className="button button-yellow" href="#inscription">Commencer mon inscription <ArrowDown size={16}/></a><div className="hero-trust"><span><Check size={15}/> 100 % en ligne</span><span><Check size={15}/> Données protégées</span></div></div><div className="hero-aside"><div className="hero-card"><div className="hero-card-icon"><ClipboardList size={22}/></div><span className="eyebrow">VOTRE DOSSIER</span><strong>Prêt en quelques minutes</strong><p>Rassemblez vos informations et votre portrait professionnel.</p><div className="progress-track"><span/></div><small><span>Étape 1 sur 1</span><span>Simple & rapide</span></small></div><div className="hero-stamp">✳ <span>votre avenir<br/>en mouvement</span></div></div></section>
    <section className="steps" id="etapes"><div className="steps-intro"><span className="eyebrow">C’EST TOUT SIMPLE</span><h2>Trois minutes.<br/><span>Un nouveau départ.</span></h2></div><div className="step-item"><span className="step-number">01</span><div><strong>Vos coordonnées</strong><p>Quelques informations pour faire connaissance.</p></div></div><div className="step-item"><span className="step-number">02</span><div><strong>Votre parcours</strong><p>Votre niveau et votre établissement.</p></div></div><div className="step-item"><span className="step-number">03</span><div><strong>Votre portrait</strong><p>Un visage pour mettre un nom sur votre dossier.</p></div></div></section>
    <section className="registration-section" id="inscription"><div className="registration-intro"><span className="eyebrow">À VOUS DE JOUER</span><h2>Faisons<br/>connaissance.</h2><p>Remplissez le formulaire. Chaque champ marqué d’un astérisque est nécessaire pour valider votre dossier.</p><div className="intro-note"><span className="note-icon">✳</span><p>Besoin d’aide ?<br/><span>Votre équipe reste à votre écoute à chaque étape.</span></p></div><div className="form-index"><span className="index-current">01</span><span className="index-line"/><span>01</span><span className="index-label">VOTRE INSCRIPTION</span></div></div><RegistrationForm/></section>
    <footer className="site-footer"><a href="#top" className="brand aicpes-brand footer-aicpes-brand" aria-label="AICPES, accueil"><img src="/aicpes-logo.png" alt="AICPES" /></a><p>Association Ivoirienne pour la Promotion de l’Éducation, de la Citoyenneté et de la Santé.</p><span>© {new Date().getFullYear()} AICPES. Tous droits réservés.</span><Link to="/admin" className="footer-admin" aria-label="Accès administrateur"><LockKeyhole size={14}/></Link></footer>
  </main>;
}
